### ISSUE TITLE
Easy way to include height/width in embed tag?

### ISSUE THREAD

**Issue by nexflo** [benjamminf/craft-embedded-assets#11]
Or how does one do this?

Thanks in advance!

**Comment by benjamminf** [comment]
Not entirely sure what you are asking, but the embedded asset model comes with width/height parameters which you can set to a div containing the embed HTML.

```twig
<div style="width: {{ embed.width }}px; height: {{ embed.height }}px">
    {{ embed.safeHtml }}
</div>
```

However, since all properties on the embed model are provided by third-parties, you can't assume any of the values will be set, or even correct.

What I tend to do is not even worry about the size of the embedded asset, and just use a solution like [Bootstrap's Responsive Embed](http://getbootstrap.com/components/#responsive-embed). Of course, I'm assuming here that the embed HTML is a simple `iframe`, but depending on which providers you use, it's a pretty safe assumption to make.
