### ISSUE TITLE
Request: Output original url

### ISSUE THREAD

**Issue by magicspon** [benjamminf/craft-embedded-assets#13]
Hello,

Would it be possible to output the original url.

For example

`{{ media.rootUrl }} === 'https://vimeo.com/44061751'`

Thanks

**Comment by benjamminf** [comment]
The reason why that property is not in there is because I wanted to adhere to the oEmbed spec. But I already added the `safeHtml` parameter (as well as the `__embeddedasset__` one) so what the hell.

I've actually just implemented it, just need to sync my commits and release.

Thanks for the request!

**Comment by magicspon** [comment]
Amazing.. many thanks

**Comment by magicspon** [comment]
Hello,

I've updated to the latest version and I'm getting errors when I try and access the requestUrl property

`{% set media = entry.video.first() %}
{{ media.title }} // works
{{ media.requestUrl }} // error`

Any ideas?

Thanks

**Comment by benjamminf** [comment]
Checkout the [usage](https://github.com/benjamminf/craft-embedded-assets#usage) section in the readme. Your `media` variable will just be the asset model – you need to call the `craft.embeddedAssets.fromAsset(media)` method to get the embedded asset model.

**Comment by magicspon** [comment]
Thanks... works like a dream...
