### ISSUE TITLE
Impossible to access an attribute ("safeHtml") on a null variable

### ISSUE THREAD

**Issue by hamishtaplin** [benjamminf/craft-embedded-assets#27]
Everything works fine locally (running in Vagrant) but for some reason, suddenly this plugin is failing on the live server when it was all working fine previously.

For example, I have an entry with a `video` field, restricted to one selection. The code below works fine locally but on the server I get `Impossible to access an attribute ("safeHtml") on a null variable`

Code: `{{craft.embeddedAssets.fromAsset(entry.video[0]).safeHtml|raw}}`

I've triple checked that `entry.video[0]` is returning a valid [AssetFileModel](https://craftcms.com/docs/templating/AssetFileModel) and it is working as expected. The JSON is [accessible](http://flamemedia.tv/beta/public/assets/video/Vimeo/embed_The-Best-of-New-Zealand-with-Nick-Honeym.json), so I don't think there are permissions issues anywhere. 

Everything is up-to-date and the server meets the minimum php requirements, etc.

How can I debug this?

**Comment by benjamminf** [comment]
It seems the `fromAsset` method is returning `null`, which could be caused by any number of things. Given that it works in a development environment, and that you have a valid asset model and permissions aren't a thing, the only thing I can think of is a misconfiguration of the asset source base URL. Can you verify that `entry.video.first.url` outputs the valid URL? Otherwise, it's probably an issue with cURL.

**Comment by hamishtaplin** [comment]
Yeah that outputs fine. This is really odd, everything worked fine previously—it's on some shared hosting currently where I don't have ssh access so I can't test curl manually.

Any ideas on where to go from here? I know this isn't a support forum but I've hit a bit of a wall and I need this to work asap!

**Comment by hamishtaplin** [comment]
@benjamminf This must have been an environment problem as it went away when I moved to a different host.
