### ISSUE TITLE
Why data is stored in JSON and not in a different table ?

### ISSUE THREAD

**Issue by alexandretillay** [benjamminf/craft-embedded-assets#33]
Hi,
First thanks for this great plugin (and for Neo). I was wondering why you chose to store data in Json file instead of filling a seperate table. Isn't it too heavy for the server to get the Json file and then decode it, especially if you have to list for example 30 videos ?

**Comment by benjamminf** [comment]
Cheers mate. There's a few reasons why I went with JSON:

- *The format is accessible.* There are often times where I want to add an embedded asset of something that can't be done by providing the URL. For example, a client wanted <iframe>'s of their custom-built 360 product tours to be embedded onto the site, but in any place you could put an asset. So what I did was just write up the JSON manually for those product tours and upload the files to Craft.
- *The files are not tied to the plugin.* If, for whatever reason, EA is no longer desired, or breaks, removing the plugin will not remove your content.
- *A cleaner interface with the existing assets system.* Since the assets system in Craft is built around actual tangible files, it made sense to use real files rather than trick the system into thinking it had a file tied to an asset but really didn't. If I had tried to trick Craft there would certainly have been many unwanted side-effects and issues.

Computers are fast. Parsing JSON is a drop in the ocean compared to everything else a server needs to do. Between parsing one and 30 JSON files, you won't notice any difference. And by using files I'm also avoiding hitting the database, which would probably be comparable in performance anyway. In the end, there's always the `{% cache %}` tag if you feel you need it.
